### ISSUE TITLE
[Tracking] This is a test tracking issue.

### ISSUE THREAD

**Issue by richeklein** [richeklein/javascript-practice#1]
## TODO

* [x] This it item 1.
* [x] This it item 2.
* [ ] This it item 3.
